function(append value)
  foreach(variable ${ARGN})
    set(${variable} "${${variable}} ${value}" PARENT_SCOPE)
  endforeach(variable)
endfunction()

include(CheckCXXCompilerFlag)

if (NOT DEFINED QT_MONKEY_COMPILER_IS_GCC_COMPATIBLE)
  if (CMAKE_COMPILER_IS_GNUCXX)
    set(QT_MONKEY_COMPILER_IS_GCC_COMPATIBLE ON)
  elseif (MSVC)
    set(QT_MONKEY_COMPILER_IS_GCC_COMPATIBLE OFF)
  elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    set (QT_MONKEY_COMPILER_IS_GCC_COMPATIBLE ON)
  endif()
endif()

check_cxx_compiler_flag("-std=c++11" CXX_SUPPORTS_CXX11)
if (CXX_SUPPORTS_CXX11)
  append("-std=c++11" CMAKE_CXX_FLAGS)
else ()
  message(FATAL_ERROR "qt_monkey requires C++11 support but the '-std=c++11' flag isn't supported.")
endif()

if (QT_MONKEY_COMPILER_IS_GCC_COMPATIBLE)
  append("-Wall" "-Wextra" "-Wformat-security" "-Wcast-align" "-Werror=format" "-Wcast-qual" CMAKE_C_FLAGS)
  append("-Wall" "-pedantic" "-Wextra" "-Wformat-security" "-Wcast-align" "-Werror=format" "-Wcast-qual" CMAKE_CXX_FLAGS)
endif ()
