Test.mouseClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab.pushButton_ModalDialog', 'Qt.LeftButton', 363, 17);
Test.pressButtonWithText('MainWindow.<class_name=QMessageBox>.qt_msgbox_buttonbox', 'OK');
Test.mouseClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab.comboBox', 'Qt.LeftButton', 135, 20);
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab.comboBox', 'item2');
//expect: Test.keyClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab.comboBox', 'Enter');
//expect: Test.keyClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab.comboBox.<class_name=QComboBoxPrivateContainer>.<class_name=QComboBoxListView>', 'Enter');
ExtAPI.pressButton("Custom Button");
Test.pressButtonWithText('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab', 'dynamic widget');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_tabbar', 'Tab 2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1');
Test.expandItemInTree('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1.1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1.2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2');
Test.expandItemInTree('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2.1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_tabbar', 'Tab 3');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_3.listWidget', 'list item1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_3.listWidget', 'list item2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_tabbar', 'Tab 4');
Test.activateItemInView('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_4.treeView', [0, 0]);
Test.activateItemInView('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_4.treeView', [0, 0]);
Test.expandItemInTreeView('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_4.treeView', [0, 0]);
Test.activateItemInView('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_4.treeView', [0, 0,0, 0]);
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_tabbar', 'Tab 5');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_5.listView', 'first');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_tabbar', 'Tab 6');
Test.mouseClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_6.lineEdit', 'Qt.LeftButton', 238, 28);
Test.keyClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_6.lineEdit', '1');
Test.mouseClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_6.textEdit.qt_scrollarea_viewport', 'Qt.LeftButton', 79, 51);
Test.keyClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_6.textEdit', '2');
Test.mouseClick('MainWindow.menubar', 'Qt.LeftButton', 25, 12);
Test.activateItem('MainWindow.menubar.menuFiles', 'Quit');
