Test.mouseClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab.pushButton', 'Qt.LeftButton', 67, 13);
Test.mouseClick('MainWindow.centralwidget.tabWidget.qt_tabwidget_tabbar', 'Qt.LeftButton', 155, 17);
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1');
Test.expandItemInTree('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1.1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '1.2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2');
Test.expandItemInTree('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2.1');
Test.activateItem('MainWindow.centralwidget.tabWidget.qt_tabwidget_stackedwidget.tab_2.treeWidget', '2');
Test.mouseClick('MainWindow.menubar', 'Qt.LeftButton', 25, 12);
Test.activateItem('MainWindow.menubar.menuFiles', 'Quit');
